filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
checks:
    php: true
coding_style:
    php:
      spaces:
        before_parentheses:
            closure_definition: true
tools:
    external_code_coverage: true