language: php

php:
  - 5.5
  - 5.6
  - 7

cache:
  directories:
    - $HOME/.composer/cache

env:
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

install:
  - composer require symfony/console:${SYMFONY_VERSION} --no-update
  - composer require symfony/event-dispatcher:${SYMFONY_VERSION} --no-update
  - composer require symfony/dom-crawler:${SYMFONY_VERSION} --no-update
  - composer require symfony/filesystem:${SYMFONY_VERSION} --no-update
  - composer require symfony/stopwatch:${SYMFONY_VERSION} --no-update
  - composer require symfony/css-selector:${SYMFONY_VERSION} --no-update
  - composer install --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpunit --group performance

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover